spring:
  #解决swagger在springboot 2.6版本以上会出现兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mybatis-plus的全局配置
  global-config:
    db-config:
      #设置主键的生成策略
      id-type: auto
      #设置实体类表的统一前缀
      table-prefix: m_
      #配置类型别名
  type-aliases-package: com.csm.myproject.entity
server:
  port: 8088


